### ISSUE TITLE
Start of week should be configurable to Monday

### ISSUE THREAD

**Issue by glancashire** [Zacharysp/CalendarHeatmap#3]
Dear Zachary 

Thanks for this beautiful control.

It would be great for using this in Europe, if there were a way to configure the start of the week to be Monday instead of Sunday.

Kind Regards
Graham

**Comment by Zacharysp** [comment]
Hi Graham,

Sorry, I haven't thought about that. Currently, the calendar always start with Sunday.
But definitely, we need to support this, I will figure it out and add the feature soon.

**Comment by glancashire** [comment]
Excellent, works great, thank you
