### ISSUE TITLE
A reload function would be nice

### ISSUE THREAD

**Issue by glancashire** [Zacharysp/CalendarHeatmap#4]
Thanks again for your control.

For usage in cells the option of reloading w/o recreating would be a great addition.

I have added one via an extension (see below), but it is of course not a clean and has to be added to your source file (private access).

Kind Regard
Graham

```swift
extension CalendarHeatmap {
    public func reload() {
        DispatchQueue.global(qos: .userInteractive).async {
            DispatchQueue.main.async { [weak self] in
                // then reload
                self?.collectionView.reloadData()
                self?.scrollToEnd()
            }
        }
    }
}
```

**Comment by Zacharysp** [comment]
Sounds great, I will add the reload function, thank you for the advice.

**Comment by glancashire** [comment]
Thank you, this solves my issue.
