### ISSUE TITLE
StartDate is being overridden

### ISSUE THREAD

**Issue by glancashire** [Zacharysp/CalendarHeatmap#8]
Hi Zachary

me again.

You are overriding the startDate, that I am lovingly calculating.

HeatmapCalendar.swift > function private func setup(completion: @escaping () -> Void) {
     startDate: self.startDate.startOfMonth(),
             
Is there an option of making this optional ;-)

Kind Regards
Graham

**Comment by Zacharysp** [comment]
yes, the first date of the calendar is actually the first date of the month based on the provided `startDate`. I thought it looks nice considered in a Calendar.

But second thought, it should not be included as a pure calendar framework, I will remove this part and let the user do the calculation.

**Comment by glancashire** [comment]
Hi Zachary

Thanks for you very constructive reaction.

Graham
